services:
  salesdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  messagebroker:
    image: rabbitmq:management
  distributedcache:
    image: redis
  sales.api:
    image: ${DOCKER_REGISTRY-}salesapi
    build:
      context: .
      dockerfile: Services/Sales/Sales.API/Dockerfile
  sales.quotesworker:
    image: ${DOCKER_REGISTRY-}salesquotesworker
    build:
      context: .
      dockerfile: Services/Sales/Sales.QuotesWorker/Dockerfile
  ui:
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI/Dockerfile
